[env:m5stack_tab5]
extends = esp32p4_base
board = m5stack-tab5-p4
board_level = extra
board_check = true
board_build.partitions = default_16MB.csv
build_unflags =
  -D HAS_BLUETOOTH
  -D MESHTASTIC_EXCLUDE_BLUETOOTH
  -D HAS_WIFI
lib_deps =
  ${esp32p4_base.lib_deps}
build_flags = 
  ${esp32p4_base.build_flags}
  -D PRIVATE_HW
  -D BOARD_HAS_PSRAM
  -I variants/esp32p4/m5stack_tab5
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D HAS_BLUETOOTH=0
  -D MESHTASTIC_EXCLUDE_WEBSERVER
  -D MESHTASTIC_EXCLUDE_MQTT
  -D CONFIG_BT_NIMBLE_EXT_ADV=1
  -D CONFIG_BT_NIMBLE_MAX_EXT_ADV_INSTANCES=2
lib_ignore =
  NonBlockingRTTTL
  NimBLE-Arduino
  libpax
build_src_filter =
 ${esp32p4_base.build_src_filter} +<../variants/esp32p4/m5stack_tab5>